config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'places#index'
  resources :places
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]
  require 'httparty'

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
    redirect_to "https://www.google.ro/maps/search/#{@place.Name}"
  end

  # GET /places/new
  def new
    @place = Place.new

  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)
    response = HTTParty.get("https://maps.googleapis.com/maps/api/place/autocomplete/json?input=#{@place.Name}&key=AIzaSyAGjxtGd68yzadXmRAe-u8ShoI7Isc_SuQ")
    parsed_response = JSON.parse(response.body)
    parsed_response['predictions'].each do |prediction|
      @place.Address = prediction['description']
      # get_photo_reference
      # puts(@image)
      break

    end
    puts(@name_of_place)
    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice:"Place was successfully created with photo reference:}" }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

#   def get_photo_reference
#     photo_response = HTTParty.get("https://maps.googleapis.com/maps/api/place/findplacefromtext/json?input=#{@place.Name}&inputtype=textquery&fields=photos&key=AIzaSyAGjxtGd68yzadXmRAe-u8ShoI7Isc_SuQ")
#     photo_parsed_response = JSON.parse(photo_response.body)
#     photo_parsed_response['candidates'].each do |candidate|
#       candidate['photos'].each do |photo|
#         @image = photo['photo_reference']
#
#       end
#
#     end
#     @image
# end
  private
    # Use callbacks to share common setup or constraints between actions.
  def set_place
    @place = Place.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def place_params
    params.require(:place).permit(:Name, :Address, :@name_of_place)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CityGuideApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Name %>
    <%= form.text_field :Name %>
  </div>

  <div class="field">
    <%= form.label :Address %>
    <%= form.text_field :Address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Heroic Features - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link href="C:/Users/Horea/Desktop/startbootstrap-heroic-features-gh-pages/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="C:/Users/Horea/Desktop/startbootstrap-heroic-features-gh-pages/css/heroic-features.css" rel="stylesheet">

</head>

<body>


<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">Timisoara City Guide</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="users/sign_up">Register</a>
        </li>

      </ul>
    </div>
  </div>
</nav>

<!-- Page Content -->
<div class="container">

  <!-- Jumbotron Header -->
  <header class="jumbotron my-4">
    <h1 class="display-4">TimisoaraGo - A city guide application</h1>
    <p class="lead"></p>
  </header>


  <% @places.each_slice(3) do |place| %>
    <div class="row text-center">
      <% place.each do |place1| %>
        <div class="col-md-4">
          <div class="card h-100">
            <tr>
              <h4>
                <%= place1.Address %>
              </h4>
              <td><%= place1.Address%></td>
            </tr>
          <img alt="" class="card-img-top" src="https://renasterea.ro/ro/wp-content/uploads/tm2021.png">
<!--            <div class="card-body">-->
<!--              <h4 class="card-title"></h4>-->
<!--              <p class="card-text">place1.Details</p>-->
<!--            </div>-->
            <div class="card-footer">
              <a href="places/<%=place1.id %>" class="btn btn-primary">Indicatii de orientare</a>
            </div>
          </div>



        </div>
      <% end %>
    </div>
  <% end %>
</div>
<!-- Bootstrap core JavaScript -->
<script src="C:/Users/Horea/Desktop/startbootstrap-heroic-features-gh-pages/vendor/jquery/jquery.min.js"></script>
<script src="C:/Users/Horea//Desktop/startbootstrap-heroic-features-gh-pages/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

</body>
</html>

app/views/places/new.html.erb
<% if user_signed_in? %>
  <h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

<% else %>

<%= flash[:alert] = "NU ESTI LOGAT" %>

 <%=  link_to('Login', new_user_session_path)%>
<% end %>

app/views/places/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @place.Name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @place.Address %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>